language: node_js
cache:
  directories:
    - ∼/.npm
node_js:
  - "14"
git:
  depth: 3
script:
  - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github_token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: gh-pages
  commit_message: "Deploy KHENDRA"
  on:
    branch: master
