lenguage: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - "14.16.1"
git:
  depth: 3
script:
  - yarn build
deploy:
  provider: pages
  edge: true
  skip-cleanup: true
  keep-history: true
  github_token: $GITHUB_TOKEN
  local-dir: dist/
  target-brach: gh-pages
  commit_message: "Deploy realease"
  on:
    branch: master
