language: node_js
cache: # información ya configurada para el proyecto
  directories:
    - ~/.npm
node_js: #version
  - "14.16.1"
git: # número de versiones (git) a guardar
  depth: 3
script: #script a ejecutar
  - yarn build
deploy:
  provider: pages #github pages
  # configuración del deploy:
  skip_cleanup: true
  keep_history: true
  # creación de un token para la conexión
  # entre Travis y GitHub:
  github_token: $GITHUB_TOKEN
  # directorio resultante de la compilación:
  # xej: /bodndel  /public ...etc
  local-dir: dist/
  # rama de publicación (sitio) de GitHub:
  tarjet-branch: gh-pages
  commit_message: "Deploy del proyecto travis"
  on:
    branch: master
