
--CONSULTAS

---CONSULTA 01/DAVID
SELECT P.ID_PERSONA, P.NOMBRE, P.APELLIDO, P.DNI,P.CORREO, P.CONTRASEÑA,
P.EDAD, P.SEXO, P.ESTADO, D.SUELDO, E.ESPECIALIZACION, C.NOMBRE_CURSO
FROM PERSONA P JOIN DOCENTE D
ON P.ID_PERSONA=D.KFK_PER JOIN ESPECIALIZACION E
ON E.ID_ESPECIALIZACION=D.KFK_ESPE JOIN CURSO C
ON C.KFK_DOCE=D.KFK_PER
WHERE P.ESTADO=1;

---CONSULTA 02/HELEN
SELECT P.ID_PERSONA, P.NOMBRE, P.APELLIDO, P.DNI,P.CORREO, P.CONTRASEÑA,
P.EDAD, P.SEXO, P.ESTADO, U.ADMIN
FROM PERSONA P JOIN USUARIO U 
ON P.ID_PERSONA=U.KFK_PER
WHERE P.ESTADO=1 AND U.ADMIN=1; 

---CONSULTA 03/KATERIN
SELECT C.NOMBRE_CLASE, M.NOMBRE_MODULO
FROM CLASE C JOIN MODULO M
ON C.ID_CLASE=m.kfk_cur
WHERE M.ID_MODULO=1;

select * from modulo;
---CONSULTA 04/GERALD
SELECT P.NOMBRE ,P.ID_PERSONA,P.SEXO
FROM PERSONA P JOIN INSCRIPCION I ON P.ID_PERSONA=I.KFK_PER
WHERE SEXO='M';

