
--FUNCIONES

---FUNCION 01/DAVID
CREATE OR REPLACE FUNCTION FK_VER_DOCENTE(P_ID_DOCENTE NUMBER)
RETURN VARCHAR2
IS
NOMBRE_DOCENTE VARCHAR2(65);
BEGIN
    SELECT NOMBRE||' '|| APELLIDO INTO NOMBRE_DOCENTE
    FROM PERSONA
    WHERE ID_PERSONA=P_ID_DOCENTE;
    RETURN NOMBRE_DOCENTE;
END;
---TEST
SELECT FK_VER_DOCENTE(KFK_DOCE) DOCENTE, NOMBRE_CURSO CURSO
FROM CURSO;

---FUNCION 02/HELEN
CREATE OR REPLACE FUNCTION FK_TRANSFORM_EDAD(P_NACIMIENTO DATE) 
RETURN NUMBER
IS
EDAD NUMBER(3);
BEGIN
    EDAD :=  ROUND((SYSDATE-P_NACIMIENTO)/360);
    RETURN EDAD;
END;
--TEST
SELECT FK_TRANSFORM_EDAD(edad), NOMBRE 
FROM PERSONA;

---FUNCION 03/KATERIN
CREATE OR REPLACE FUNCTION FK_TRANSFORM_SEXO(P_ID_PERSONA NUMBER)
RETURN VARCHAR2
IS
SEXO VARCHAR2(20);
SEXO_RETURN VARCHAR2(20);
BEGIN
    SELECT SEXO INTO SEXO 
    FROM PERSONA
    WHERE ID_PERSONA=P_ID_PERSONA;
    IF SEXO = 'F' THEN
        SEXO_RETURN := 'FEMENINO';
    ELSE
        SEXO_RETURN := 'MASCULINO';
    END IF;
    RETURN SEXO_RETURN;
END;
--TEST
SELECT FK_TRANSFORM_SEXO(ID_PERSONA), NOMBRE 
FROM PERSONA;

---FUNCION 04/GERALD
CREATE OR REPLACE FUNCTION FK_TRANSFORM_VALORACION(P_ID_VAL NUMBER)
RETURN VARCHAR2
IS
VALORACION VARCHAR2(5);
VALORACION_RETURN VARCHAR2(5);
BEGIN
    SELECT VALORACION INTO VALORACION
    FROM INSCRIPCION
    WHERE ID_INSCRIPTION=P_ID_VAL;
    IF VALORACION = 2 THEN
        VALORACION_RETURN := 'Dos';
    END IF;
    RETURN VALORACION_RETURN;
END;
--TEST
SELECT FK_TRANSFORM_VALORACION(ID_INSCRIPTION) 
FROM INSCRIPCION;

